apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadfusa7756-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadfusa7756-tenant-component
    app.kubernetes.io/part-of: loadfusa7756-tenant-app
  name: loadfusa7756-tenant-component
  namespace: loadfusa7756-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadfusa7756-tenant-component
    weight: null
status: {}
